
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.0
    container_name: keycloak
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://db:3306/${KEYCLOAK_DB}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .providers:/opt/keycloak/providers
    ports:
      - 8080:8080
      
  db:
    image: mysql:9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${STORAGE_DB_PASSWORD}
      MYSQL_DATABASE: ${STORAGE_DB}
      MYSQL_USER: ${STORAGE_DB_USER}
      MYSQL_PASSWORD: ${STORAGE_DB_PASSWORD}
    volumes:
      - storage_db_storage:/var/lib/mysql
      - ./.initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${STORAGE_DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
     - "3306:3306"


volumes:
  storage_db_storage: